@startuml
set separator none
title SpringModulithApplication

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("SpringModulithApplication.SpringModulithApplication_boundary", "SpringModulithApplication", $tags="") {
  Component(SpringModulithApplication.SpringModulithApplication.Doctor, "Doctor", $techn="Module", $descr="", $tags="", $link="")
  Component(SpringModulithApplication.SpringModulithApplication.core, "core", $techn="Module", $descr="", $tags="", $link="")
  Component(SpringModulithApplication.SpringModulithApplication.Patient, "Patient", $techn="Module", $descr="", $tags="", $link="")
  Component(SpringModulithApplication.SpringModulithApplication.Hospital, "Hospital", $techn="Module", $descr="", $tags="", $link="")
}

Rel(SpringModulithApplication.SpringModulithApplication.Patient, SpringModulithApplication.SpringModulithApplication.core, "listens to", $techn="", $tags="", $link="")
Rel(SpringModulithApplication.SpringModulithApplication.Doctor, SpringModulithApplication.SpringModulithApplication.core, "listens to", $techn="", $tags="", $link="")
Rel(SpringModulithApplication.SpringModulithApplication.Hospital, SpringModulithApplication.SpringModulithApplication.core, "depends on", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml