@startuml
set separator none
title Author

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("SpringModulithApplication.SpringModulithApplication_boundary", "SpringModulithApplication", $tags="") {
  Component(SpringModulithApplication.SpringModulithApplication.Author, "Author", $techn="Module", $descr="", $tags="", $link="")
}


SHOW_LEGEND(true)
@enduml